apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: dthtien/k8s-playaround:latest
          command: ['rails']
          args: ['db:migrate']
