apiVersion: v1
kind: Service
metadata:
  name: k8s-playaround-service
spec:
  type: LoadBalancer
  selector:
    app: main-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
