apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: sidekiq

    template:
      metadata:
        labels:
          app: sidekiq

      spec:
        containers:
        - name: sidekiq
          image: dthtien/k8s-playaround:latest
          command: ["sidekiq"]
          arguments: ["-c", "config/sidekiq.yml"]
